"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { Bookmark, Building2, CalendarDays, Check, CheckCircle2, ChevronLeft, ChevronRight, Heart, MapPin, MessageCircle, Phone, ShieldCheck, Sparkles, X } from "lucide-react";
import { MobileLayout } from "@/components/layout/MobileLayout";

interface IjamanDetail {
  id: string; title: string; category: string; address: string; deposit: string; monthly: string;
  originalDeposit: string; support: string; supportPeriod: string; moveIn: string; area: string;
  floor: string; maintenance: string; features: string[]; description: string; views: string;
  likes: number; broker: { office: string; manager: string; phone: string; address: string; registration: string };
  images: string[]; vip?: boolean;
}

const IMAGE = {
  room: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&h=700&fit=crop",
  office: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&h=700&fit=crop",
  apartment: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&h=700&fit=crop",
  city: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&h=700&fit=crop",
  street: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=900&h=700&fit=crop",
  house: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&h=700&fit=crop",
};

const DETAILS: Record<string, IjamanDetail> = {
  vip1: { id: "vip1", title: "신혼부부 추천 풀옵션 아파트", category: "아파트 · 월세", address: "서울 마포구 월드컵북로 120", deposit: "200만원", monthly: "50만원", originalDeposit: "300만원", support: "월 이자 최대 20만원 지원", supportPeriod: "입주 후 12개월", moveIn: "즉시 입주 가능", area: "전용 84㎡ (25.4평)", floor: "12층 / 24층", maintenance: "월 30만원", features: ["입주청소 지원", "블라인드 설치", "풀옵션", "역세권"], description: "신혼부부와 직장인에게 추천하는 풀옵션 매물입니다. 보증금 부담을 낮추고 계약 기간 동안 월 이자 일부를 지원합니다.", views: "5,678", likes: 123, vip: true, broker: { office: "마피프라임공인중개사", manager: "김마피", phone: "010-2345-6789", address: "서울 마포구 월드컵북로 118", registration: "11440-2026-00123" }, images: [IMAGE.room, IMAGE.apartment, IMAGE.house] },
  vip2: { id: "vip2", title: "역세권 풀옵션 오피스텔", category: "오피스텔 · 월세", address: "서울 강남구 테헤란로 152", deposit: "150만원", monthly: "35만원", originalDeposit: "200만원", support: "월 이자 최대 15만원 지원", supportPeriod: "입주 후 10개월", moveIn: "2026년 10월 5일 이후", area: "전용 59㎡ (17.8평)", floor: "8층 / 18층", maintenance: "월 20만원", features: ["풀옵션", "입주청소 지원", "역 도보 3분"], description: "업무지구 접근성이 좋은 오피스텔입니다. 계약 확인 후 이자 지원 조건과 입주 일정을 중개사가 안내합니다.", views: "3,421", likes: 87, vip: true, broker: { office: "강남센트럴공인중개사", manager: "이현수", phone: "010-4567-8123", address: "서울 강남구 테헤란로 150", registration: "11680-2025-00456" }, images: [IMAGE.office, IMAGE.city, IMAGE.room] },
  "1": { id: "1", title: "언주역 도보 5분 넓은 아파트", category: "아파트 · 월세", address: "서울 강남구 논현로 551", deposit: "300만원", monthly: "4,000만원", originalDeposit: "300만원", support: "계약 조건에 따라 이자 지원 협의", supportPeriod: "최대 12개월", moveIn: "즉시 협의", area: "전용 142.68㎡ (43.1평)", floor: "6층 / 15층", maintenance: "월 50만원", features: ["언주역 도보 5분", "넓은 평수", "남향"], description: "강남 업무권역과 가까운 넓은 평형 매물입니다. 세부 보증금과 월 부담액은 상담 시 조정할 수 있습니다.", views: "3", likes: 0, broker: { office: "언주좋은집공인중개사", manager: "박지훈", phone: "010-7788-1234", address: "서울 강남구 논현로 549", registration: "11680-2024-00231" }, images: [IMAGE.apartment, IMAGE.room, IMAGE.city] },
  "2": { id: "2", title: "역삼역 도보 3분 신축 오피스텔", category: "오피스텔 · 전세", address: "서울 강남구 역삼로 201", deposit: "3억 5,000만원", monthly: "없음", originalDeposit: "3억 5,000만원", support: "전세대출 이자 조건 상담", supportPeriod: "금융사 심사 기준", moveIn: "2026년 11월 협의", area: "전용 28.5㎡ (8.6평)", floor: "10층 / 16층", maintenance: "월 15만원", features: ["신축", "풀옵션", "역삼역 도보 3분"], description: "1인 직장인에게 적합한 신축 오피스텔 전세 매물입니다.", views: "12", likes: 3, broker: { office: "역삼스마트부동산", manager: "최유진", phone: "010-9876-5522", address: "서울 강남구 역삼로 199", registration: "11680-2026-00302" }, images: [IMAGE.office, IMAGE.room, IMAGE.city] },
  "3": { id: "3", title: "강남역 코너 상가", category: "상가 · 월세", address: "서울 강남구 강남대로 421", deposit: "5,000만원", monthly: "250만원", originalDeposit: "6,000만원", support: "보증금 대출 이자 일부 지원", supportPeriod: "최대 6개월", moveIn: "즉시 입점 가능", area: "전용 85.5㎡ (25.9평)", floor: "2층 / 8층", maintenance: "별도 협의", features: ["강남역 도보 2분", "코너 자리", "렌트프리 3개월"], description: "음식점, 휴대폰 매장, IT 기업에 적합한 유동 인구 많은 코너 상가입니다.", views: "45", likes: 8, broker: { office: "강남상가전문부동산", manager: "정민호", phone: "010-5588-7711", address: "서울 강남구 강남대로 419", registration: "11680-2025-00711" }, images: [IMAGE.street, IMAGE.city, IMAGE.office] },
  "4": { id: "4", title: "가산디지털단지 지식산업센터", category: "지식산업센터 · 월세", address: "경기 광명시 일직로 43", deposit: "3,000만원", monthly: "180만원", originalDeposit: "3,500만원", support: "사업자 대출 이자 조건 상담", supportPeriod: "금융사 심사 기준", moveIn: "2026년 10월 협의", area: "전용 165.2㎡ (50평)", floor: "8층 / 20층", maintenance: "월 25만원", features: ["가산디지털단지역", "주차 편리", "IT 기업 추천"], description: "업무 공간과 물류 접근성을 함께 갖춘 지식산업센터 매물입니다.", views: "28", likes: 5, broker: { office: "가산비즈공인중개사", manager: "오세진", phone: "010-3322-9041", address: "경기 광명시 일직로 41", registration: "41210-2026-00091" }, images: [IMAGE.city, IMAGE.office, IMAGE.apartment] },
};

const FALLBACK: IjamanDetail = { ...DETAILS.vip1, id: "fallback", title: "이자 지원 조건 협의 매물", vip: false };

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="rounded-[20px] border border-[var(--line)] bg-white p-5 shadow-[0_5px_18px_rgba(27,23,38,.04)]"><h2 className="mb-4 text-[16px] font-black tracking-[-.3px] text-[var(--brand-ink)]">{title}</h2>{children}</section>;
}

export default function IjamanDetailPage() {
  const params = useParams<{ id: string }>();
  const item = DETAILS[params.id] ?? { ...FALLBACK, id: params.id };
  const [slide, setSlide] = useState(0);
  const [liked, setLiked] = useState(false);
  const [contact, setContact] = useState<"menu" | "chat" | "sent" | null>(null);

  return <MobileLayout hideNav>
    <header className="sticky top-0 z-30 flex h-[60px] items-center justify-between bg-[var(--brand-ink)] px-4 text-white"><Link href="/category/ijaman" aria-label="목록으로"><ChevronLeft className="h-6 w-6" /></Link><span className="text-[16px] font-black">이자만 매물 상세</span><button type="button" aria-label="관심 매물" onClick={() => setLiked((value) => !value)} className="grid h-10 w-10 place-items-center rounded-full bg-white/10"><Heart className={liked ? "h-5 w-5 fill-[#E4C577] text-[#E4C577]" : "h-5 w-5"} /></button></header>
    <div className="pb-28">
      <div className="relative aspect-[4/3] bg-[#E9E6EE]"><Image src={item.images[slide]} alt={`${item.title} ${slide + 1}`} fill priority sizes="430px" className="object-cover" /><div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-black/45 to-transparent" /><button type="button" aria-label="이전 사진" onClick={() => setSlide((slide - 1 + item.images.length) % item.images.length)} className="absolute left-3 top-1/2 grid h-9 w-9 -translate-y-1/2 place-items-center rounded-full bg-black/35 text-white backdrop-blur"><ChevronLeft className="h-4 w-4" /></button><button type="button" aria-label="다음 사진" onClick={() => setSlide((slide + 1) % item.images.length)} className="absolute right-3 top-1/2 grid h-9 w-9 -translate-y-1/2 place-items-center rounded-full bg-black/35 text-white backdrop-blur"><ChevronRight className="h-4 w-4" /></button><span className="absolute bottom-3 right-3 rounded-full bg-black/50 px-2.5 py-1 text-[10px] font-bold text-white">{slide + 1} / {item.images.length}</span></div>
      <div className="space-y-4 px-4 pt-4">
        <div className="rounded-[22px] bg-white p-5 shadow-[0_7px_24px_rgba(27,23,38,.06)]">
          <div className="flex items-center gap-2">{item.vip && <span className="gold-fill rounded-full px-2.5 py-1 text-[9px] font-black">VIP</span>}<span className="text-[11px] font-bold text-[var(--brand-purple)]">{item.category}</span><span className="ml-auto flex items-center gap-1 text-[10px] text-[var(--text-muted)]"><Bookmark className="h-3.5 w-3.5" /> {item.likes}</span></div>
          <h1 className="mt-3 text-[21px] font-black leading-[1.3] tracking-[-.6px] text-[var(--brand-ink)]">{item.title}</h1><p className="mt-2 flex items-center gap-1.5 text-[12px] text-[var(--text-muted)]"><MapPin className="h-4 w-4 text-[var(--brand-purple)]" />{item.address}</p>
          <div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-[15px] bg-[var(--brand-purple-soft)] p-3"><p className="text-[10px] font-bold text-[var(--brand-purple)]">보증금</p><p className="mt-1 text-[17px] font-black text-[var(--brand-ink)]">{item.deposit}</p></div><div className="rounded-[15px] bg-[#FFF7E7] p-3"><p className="text-[10px] font-bold text-[#98701E]">월 부담액</p><p className="mt-1 text-[17px] font-black text-[var(--brand-ink)]">{item.monthly}</p></div></div>
          <p className="mt-3 text-[10px] text-[var(--text-muted)]">조회 {item.views} · 등록번호 IJ-{item.id.toUpperCase()} · 정보 확인 2026.09.22</p>
        </div>

        <section className="relative overflow-hidden rounded-[20px] bg-[var(--brand-ink)] p-5 text-white"><div className="absolute -right-8 -top-10 h-36 w-36 rounded-full bg-[var(--brand-gold)]/20 blur-3xl" /><div className="relative flex items-start gap-3"><span className="gold-fill grid h-11 w-11 shrink-0 place-items-center rounded-[14px]"><Sparkles className="h-5 w-5" /></span><div><p className="text-[10px] font-black tracking-[1px] text-[#E9D6A0]">INTEREST SUPPORT</p><h2 className="mt-1 text-[17px] font-black">{item.support}</h2><p className="mt-2 text-[11.5px] leading-5 text-white/60">지원 기간 {item.supportPeriod}<br />계약 및 금융 심사 결과에 따라 지원 범위가 달라질 수 있습니다.</p></div></div></section>

        <Section title="가격 · 입주 조건"><div className="overflow-hidden rounded-xl border border-[var(--line)]">{[["최초 보증금", item.originalDeposit], ["현재 보증금", item.deposit], ["월 부담액", item.monthly], ["관리비", item.maintenance], ["입주 가능일", item.moveIn]].map(([label, value], index) => <div key={label} className={cnRow(index)}><span className="w-28 shrink-0 bg-[var(--surface-muted)] px-4 py-3 text-[12px] font-bold text-[var(--text-muted)]">{label}</span><span className="flex-1 px-4 py-3 text-right text-[13px] font-bold text-[var(--brand-ink)]">{value}</span></div>)}</div></Section>
        <Section title="매물 정보"><div className="grid grid-cols-2 gap-2">{[["면적", item.area], ["층수", item.floor], ["입주", item.moveIn], ["관리비", item.maintenance]].map(([label, value]) => <div key={label} className="rounded-[14px] bg-[var(--surface-muted)] p-3"><p className="text-[10px] font-bold text-[var(--text-muted)]">{label}</p><p className="mt-1 text-[12.5px] font-black text-[var(--brand-ink)]">{value}</p></div>)}</div><div className="mt-3 flex flex-wrap gap-2">{item.features.map((feature) => <span key={feature} className="inline-flex items-center gap-1 rounded-full bg-[#EAF8EF] px-2.5 py-1.5 text-[10.5px] font-bold text-[#188650]"><Check className="h-3 w-3" />{feature}</span>)}</div><p className="mt-4 text-[13px] leading-6 text-[#625B6E]">{item.description}</p></Section>
        <Section title="중개사 정보"><div className="flex items-center gap-3"><span className="gold-fill grid h-12 w-12 shrink-0 place-items-center rounded-[15px]"><Building2 className="h-6 w-6" /></span><div><p className="text-[14px] font-black text-[var(--brand-ink)]">{item.broker.office}</p><p className="mt-1 flex items-center gap-1 text-[10.5px] font-bold text-[#188650]"><ShieldCheck className="h-3.5 w-3.5" />MAPI 인증 중개업소</p></div></div><div className="mt-4 space-y-2 border-t border-[var(--line)] pt-4 text-[12px]"><p><span className="inline-block w-20 text-[var(--text-muted)]">담당 중개사</span><b>{item.broker.manager}</b></p><p><span className="inline-block w-20 text-[var(--text-muted)]">사무소 주소</span>{item.broker.address}</p><p><span className="inline-block w-20 text-[var(--text-muted)]">등록번호</span>{item.broker.registration}</p></div></Section>
        <div className="flex items-center gap-2 rounded-[16px] border border-[#F1E2B6] bg-[#FFFBEB] p-4 text-[11px] leading-5 text-[#74633C]"><CalendarDays className="h-5 w-5 shrink-0" />현장 방문 전 가격과 이자 지원 조건이 유효한지 중개사에게 다시 확인해 주세요.</div>
      </div>
    </div>

    {contact && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45" onClick={() => setContact(null)}><div className="w-full max-w-[430px] rounded-t-[26px] bg-white p-5 pb-7" onClick={(event) => event.stopPropagation()}><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-black tracking-[1px] text-[var(--brand-purple)]">MAPI CONTACT</p><h2 className="mt-1 text-[19px] font-black text-[var(--brand-ink)]">{contact === "menu" ? "중개사에게 문의하기" : contact === "chat" ? "채팅 문의 작성" : "문의가 접수되었습니다"}</h2></div><button type="button" aria-label="닫기" onClick={() => setContact(null)} className="grid h-9 w-9 place-items-center rounded-full bg-[var(--surface-muted)]"><X className="h-4 w-4" /></button></div>{contact === "menu" && <div className="space-y-3"><a href={`tel:${item.broker.phone}`} className="flex items-center gap-3 rounded-[16px] border border-[var(--line)] p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--brand-purple-soft)]"><Phone className="h-5 w-5 text-[var(--brand-purple)]" /></span><span><b className="block text-[14px] text-[var(--brand-ink)]">전화 문의</b><span className="text-[12px] text-[var(--text-muted)]">{item.broker.manager} · {item.broker.phone}</span></span></a><button type="button" onClick={() => setContact("chat")} className="flex w-full items-center gap-3 rounded-[16px] border border-[var(--line)] p-4 text-left"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#FFF7E7]"><MessageCircle className="h-5 w-5 text-[#9D7530]" /></span><span><b className="block text-[14px] text-[var(--brand-ink)]">채팅 문의</b><span className="text-[12px] text-[var(--text-muted)]">이자 지원과 입주 조건을 문의합니다.</span></span></button></div>}{contact === "chat" && <div><textarea aria-label="문의 내용" defaultValue={`안녕하세요. ${item.title}의 이자 지원 조건과 입주 가능일을 문의드립니다.`} className="h-28 w-full resize-none rounded-[15px] border border-[var(--line)] p-4 text-[13px] leading-6 outline-none focus:border-[var(--brand-purple)]" /><button type="button" onClick={() => setContact("sent")} className="mt-3 w-full rounded-[15px] bg-[linear-gradient(135deg,#7B2FF7,#A855F7)] py-4 text-[15px] font-black text-white">문의 보내기</button></div>}{contact === "sent" && <div className="py-3 text-center"><span className="gold-fill mx-auto grid h-16 w-16 place-items-center rounded-[22px]"><CheckCircle2 className="h-8 w-8" /></span><p className="mt-4 text-[13px] leading-6 text-[var(--text-muted)]">중개사에게 문의를 전달했습니다.<br />답변이 오면 알림으로 알려드립니다.</p><button type="button" onClick={() => setContact(null)} className="mt-5 w-full rounded-[15px] bg-[var(--brand-ink)] py-3.5 text-[14px] font-black text-white">확인</button></div>}</div></div>}

    <div className="fixed bottom-0 left-1/2 z-40 flex w-full max-w-[430px] -translate-x-1/2 gap-2.5 border-t border-[var(--line)] bg-white/95 px-4 pb-[max(14px,env(safe-area-inset-bottom))] pt-3 backdrop-blur"><Link href="/favorites" className="grid h-12 w-12 shrink-0 place-items-center rounded-[14px] border border-[var(--line)]"><Bookmark className="h-5 w-5 text-[var(--text-muted)]" /></Link><a href={`tel:${item.broker.phone}`} className="flex h-12 flex-1 items-center justify-center gap-1.5 rounded-[14px] border border-[var(--brand-purple)] text-[14px] font-black text-[var(--brand-purple)]"><Phone className="h-4 w-4" />전화 문의</a><button type="button" onClick={() => setContact("menu")} className="flex h-12 flex-1 items-center justify-center gap-1.5 rounded-[14px] bg-[linear-gradient(135deg,#7B2FF7,#A855F7)] text-[14px] font-black text-white shadow-[0_6px_16px_rgba(123,47,247,.3)]"><MessageCircle className="h-4 w-4" />문의하기</button></div>
  </MobileLayout>;
}

function cnRow(index: number) {
  return `flex ${index > 0 ? "border-t border-[var(--line)]" : ""}`;
}
