"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Building2, CalendarDays, Check, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardCheck, ImagePlus, MapPin, ShieldCheck, Upload, X } from "lucide-react";
import { MobileLayout } from "@/components/layout/MobileLayout";
import { PageHeader } from "@/components/layout/PageHeader";
import { cn } from "@/lib/utils";

export type ListingKind = "bunyanggwon" | "ijaman";
type FormState = { propertyType: string; complexName: string; address: string; buildingNo: string; unitNo: string; area: string; floor: string; direction: string; salePrice: string; askingPrice: string; benefitType: string; deposit: string; monthlyRent: string; supportAmount: string; supportPeriod: string; moveInDate: string; loan: string; description: string };

const INITIAL: Record<ListingKind, FormState> = {
  bunyanggwon: { propertyType: "아파트", complexName: "광교 중흥S클래스", address: "경기 수원시 영통구 광교호수공원로 277", buildingNo: "101", unitNo: "1201", area: "84㎡", floor: "12", direction: "남향", salePrice: "85000", askingPrice: "82000", benefitType: "", deposit: "", monthlyRent: "", supportAmount: "", supportPeriod: "", moveInDate: "2026-12-01", loan: "중도금 대출 승계 가능", description: "호수 조망이 가능한 남향 세대입니다. 일정과 조건은 협의 가능합니다." },
  ijaman: { propertyType: "오피스텔", complexName: "광교 더샵 레이크시티", address: "경기 수원시 영통구 광교중앙로 145", buildingNo: "B", unitNo: "1804", area: "42㎡", floor: "18", direction: "남동향", salePrice: "", askingPrice: "", benefitType: "렌트프리", deposit: "1000", monthlyRent: "85", supportAmount: "255", supportPeriod: "3개월", moveInDate: "2026-10-01", loan: "", description: "입주 후 3개월 렌트프리 조건입니다. 업무시설과 교통 접근성이 좋습니다." },
};

const INPUT = "w-full rounded-[14px] border border-[var(--line)] bg-white px-4 py-3.5 text-[14px] font-semibold text-[var(--text-strong)] outline-none transition focus:border-[var(--brand-purple)] placeholder:text-[#B7B1C0]";

function Field({ label, required, hint, children }: { label: string; required?: boolean; hint?: string; children: React.ReactNode }) {
  return <label className="block"><span className="mb-2 flex items-center gap-1 text-[12.5px] font-extrabold text-[var(--text-muted)]">{label}{required && <span className="text-[var(--danger)]">*</span>}{hint && <span className="ml-auto font-medium text-[#A49EAD]">{hint}</span>}</span>{children}</label>;
}

function Card({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return <section className="rounded-[22px] border border-white bg-white p-5 shadow-[0_7px_22px_rgba(27,23,38,.055)]"><div className="mb-5 flex items-center gap-3"><span className="gold-fill grid h-9 w-9 place-items-center rounded-[12px]">{icon}</span><h2 className="text-[16px] font-black tracking-[-.3px] text-[var(--brand-ink)]">{title}</h2></div><div className="space-y-4">{children}</div></section>;
}

function Choice({ active, children, onClick }: { active: boolean; children: React.ReactNode; onClick: () => void }) {
  return <button type="button" onClick={onClick} className={cn("rounded-[13px] border px-3 py-3 text-[13px] font-extrabold transition active:scale-[.98]", active ? "border-[var(--brand-purple)] bg-[var(--brand-purple)] text-white shadow-[0_5px_14px_rgba(123,47,247,.22)]" : "border-[var(--line)] bg-white text-[var(--text-muted)]")}>{children}</button>;
}

function SummaryRow({ label, value, strong }: { label: string; value: string; strong?: boolean }) {
  return <div className="flex items-start justify-between gap-4 border-b border-[var(--line)] py-3.5 last:border-0"><span className="shrink-0 text-[12px] font-semibold text-[var(--text-muted)]">{label}</span><span className={cn("text-right text-[13px] font-bold text-[var(--text-strong)]", strong && "gold-text text-[15px] font-black")}>{value || "-"}</span></div>;
}

function formatMoney(value: string) { const number = Number(value.replace(/,/g, "")); return Number.isFinite(number) && number > 0 ? `${number.toLocaleString("ko-KR")}만원` : "-"; }

export function ListingRegistrationFlow({ kind }: { kind: ListingKind }) {
  const isTransfer = kind === "bunyanggwon";
  const [step, setStep] = useState(1);
  const [form, setForm] = useState<FormState>(INITIAL[kind]);
  const [files, setFiles] = useState<string[]>([]);
  const [error, setError] = useState("");
  const premium = useMemo(() => { const asking = Number(form.askingPrice); const sale = Number(form.salePrice); if (!asking || !sale) return "-"; const gap = asking - sale; return gap === 0 ? "무피" : `${gap < 0 ? "마피" : "프리미엄"} ${Math.abs(gap).toLocaleString("ko-KR")}만원`; }, [form.askingPrice, form.salePrice]);
  const update = (key: keyof FormState, value: string) => { setForm((previous) => ({ ...previous, [key]: value })); setError(""); };
  const next = () => {
    const common = [form.complexName, form.address, form.buildingNo, form.unitNo, form.area];
    const deal = isTransfer ? [form.salePrice, form.askingPrice, form.direction] : [form.benefitType, form.deposit, form.monthlyRent, form.supportPeriod];
    if (step === 1 && [...common, ...deal].some((value) => !value.trim())) { setError("필수 항목을 모두 입력해 주세요."); return; }
    if (step === 2 && !form.description.trim()) { setError("매물 설명을 입력해 주세요."); return; }
    setStep((current) => Math.min(current + 1, 4)); setError(""); window.scrollTo({ top: 0, behavior: "smooth" });
  };
  const previous = () => { setStep((current) => Math.max(current - 1, 1)); setError(""); window.scrollTo({ top: 0, behavior: "smooth" }); };

  if (step === 4) return (
    <MobileLayout hideNav><PageHeader title="등록 접수 완료" /><div className="flex min-h-[calc(100vh-61px)] flex-col px-5 pb-10 pt-12">
      <div className="text-center"><div className="gold-fill mx-auto grid h-20 w-20 place-items-center rounded-[28px]"><CheckCircle2 className="h-10 w-10" strokeWidth={2.2} /></div><span className="mt-6 inline-block rounded-full bg-[var(--brand-purple-soft)] px-3 py-1.5 text-[10px] font-black tracking-[.6px] text-[var(--brand-purple)]">DEMO RECEIVED</span><h1 className="mt-3 text-[24px] font-black tracking-[-.8px] text-[var(--brand-ink)]">매물 등록을 접수했어요</h1><p className="mt-2 text-[13px] leading-6 text-[var(--text-muted)]">{form.complexName} {form.buildingNo}동 {form.unitNo}호<br />검토 후 목록에 공개되는 흐름을 확인할 수 있습니다.</p></div>
      <div className="mt-8 rounded-[20px] border border-[#D7AE54]/30 bg-[#211B29] p-5 text-white shadow-[0_12px_28px_rgba(27,23,38,.15)]"><div className="flex items-center gap-2 text-[13px] font-black"><ShieldCheck className="h-4 w-4 text-[#E7C66D]" /> 1차 전달용 데모 안내</div><p className="mt-2 text-[11.5px] leading-5 text-white/60">현재는 화면과 클릭 흐름을 확인하는 데모입니다. 실제 저장, 관리자 승인, 알림 발송은 개발사의 API 연동 후 동작합니다.</p></div>
      <div className="mt-auto space-y-3 pt-10"><Link href="/register/list" className="flex w-full items-center justify-center rounded-[16px] bg-[var(--brand-purple)] py-4 text-[15px] font-black text-white shadow-[0_8px_20px_rgba(123,47,247,.26)]">내 등록 매물 보기</Link><Link href={isTransfer ? "/category/bunyanggwon" : "/category/ijaman"} className="flex w-full items-center justify-center rounded-[16px] border border-[var(--line)] bg-white py-4 text-[14px] font-extrabold text-[var(--brand-ink)]">매물 목록으로 돌아가기</Link><Link href="/register/new" className="block py-2 text-center text-[12px] font-bold text-[var(--text-muted)]">다른 매물 등록하기</Link></div>
    </div></MobileLayout>
  );

  const labels = ["기본 정보", "사진·설명", "등록 검토"];
  return <MobileLayout hideNav><PageHeader title={isTransfer ? "분양권 전매 등록" : "이자만 매물 등록"} right={<button type="button" onClick={() => window.alert("입력 내용이 임시 저장되었습니다.\n(데모 화면)")} className="text-[11px] font-extrabold text-[var(--brand-purple)]">임시저장</button>} />
    <div className="border-b border-[var(--line)] bg-white px-5 pb-4 pt-2"><div className="flex items-center">{labels.map((label, index) => { const number = index + 1; return <div key={label} className={cn("flex items-center", index < 2 && "flex-1")}><div className="flex flex-col items-center gap-1"><span className={cn("grid h-7 w-7 place-items-center rounded-full text-[11px] font-black", number <= step ? "gold-fill" : "bg-[#ECE9F0] text-[#A39DAB]")}>{number < step ? <Check className="h-3.5 w-3.5" /> : number}</span><span className={cn("whitespace-nowrap text-[9.5px] font-bold", number === step ? "text-[var(--brand-ink)]" : "text-[#A39DAB]")}>{label}</span></div>{index < 2 && <span className={cn("mx-2 mb-5 h-px flex-1", number < step ? "bg-[var(--brand-gold)]" : "bg-[var(--line)]")} />}</div>; })}</div></div>
    <div className="space-y-4 px-4 pb-[122px] pt-4">
      {error && <div role="alert" className="rounded-[14px] border border-[#F4C8CB] bg-[#FFF1F2] px-4 py-3 text-[12.5px] font-bold text-[var(--danger)]">{error}</div>}
      {step === 1 && <>
        <div className="relative overflow-hidden rounded-[22px] bg-[var(--brand-ink)] p-5 text-white"><div className="absolute -right-6 -top-8 h-28 w-28 rounded-full bg-[var(--brand-purple)]/25 blur-2xl" /><span className="gold-text text-[10px] font-black tracking-[1.2px]">MAPI LISTING</span><h1 className="mt-2 text-[20px] font-black tracking-[-.5px]">{isTransfer ? "분양권 조건을 정확하게" : "실질 혜택이 보이도록"}</h1><p className="mt-1 text-[11.5px] leading-5 text-white/55">샘플 정보가 입력되어 있어 바로 등록 흐름을 확인할 수 있습니다.</p></div>
        <Card icon={<Building2 className="h-[18px] w-[18px]" />} title="매물 기본 정보">
          <Field label="매물 유형" required><div className="grid grid-cols-2 gap-2">{["아파트", "오피스텔"].map((value) => <Choice key={value} active={form.propertyType === value} onClick={() => update("propertyType", value)}>{value}</Choice>)}</div></Field>
          <Field label="단지·건물명" required><input value={form.complexName} onChange={(e) => update("complexName", e.target.value)} className={INPUT} /></Field>
          <Field label="소재지" required><div className="relative"><MapPin className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--brand-purple)]" /><input value={form.address} onChange={(e) => update("address", e.target.value)} className={cn(INPUT, "pl-10")} /></div></Field>
          <div className="grid grid-cols-2 gap-2"><Field label="동" required><input value={form.buildingNo} onChange={(e) => update("buildingNo", e.target.value)} className={INPUT} /></Field><Field label="호" required><input value={form.unitNo} onChange={(e) => update("unitNo", e.target.value)} className={INPUT} /></Field></div>
          <div className="grid grid-cols-3 gap-2"><Field label="면적" required><input value={form.area} onChange={(e) => update("area", e.target.value)} className={INPUT} /></Field><Field label="층"><input value={form.floor} onChange={(e) => update("floor", e.target.value)} className={INPUT} /></Field><Field label="방향" required><select value={form.direction} onChange={(e) => update("direction", e.target.value)} className={INPUT}>{["남향", "남동향", "남서향", "동향", "서향"].map((v) => <option key={v}>{v}</option>)}</select></Field></div>
        </Card>
        <Card icon={<CircleDollarSign className="h-[18px] w-[18px]" />} title={isTransfer ? "분양·매매 조건" : "이자만 혜택 조건"}>
          {isTransfer ? <><div className="grid grid-cols-2 gap-2"><Field label="분양가" required hint="만원"><input inputMode="numeric" value={form.salePrice} onChange={(e) => update("salePrice", e.target.value)} className={INPUT} /></Field><Field label="희망 매매가" required hint="만원"><input inputMode="numeric" value={form.askingPrice} onChange={(e) => update("askingPrice", e.target.value)} className={INPUT} /></Field></div><div className="rounded-[14px] bg-[var(--brand-purple-soft)] px-4 py-3"><span className="text-[11px] font-bold text-[var(--text-muted)]">자동 계산 프리미엄</span><strong className="float-right text-[13px] font-black text-[var(--brand-purple)]">{premium}</strong></div><Field label="대출·승계 조건"><select value={form.loan} onChange={(e) => update("loan", e.target.value)} className={INPUT}>{["중도금 대출 승계 가능", "대출 없음", "조건 협의"].map((v) => <option key={v}>{v}</option>)}</select></Field></>
          : <><Field label="제공 혜택" required><div className="grid grid-cols-3 gap-2">{["렌트프리", "월세 할인", "인테리어 지원"].map((v) => <Choice key={v} active={form.benefitType === v} onClick={() => update("benefitType", v)}>{v}</Choice>)}</div></Field><div className="grid grid-cols-2 gap-2"><Field label="보증금" required hint="만원"><input inputMode="numeric" value={form.deposit} onChange={(e) => update("deposit", e.target.value)} className={INPUT} /></Field><Field label="월 임대료" required hint="만원"><input inputMode="numeric" value={form.monthlyRent} onChange={(e) => update("monthlyRent", e.target.value)} className={INPUT} /></Field></div><div className="grid grid-cols-2 gap-2"><Field label="총 지원금" hint="만원"><input inputMode="numeric" value={form.supportAmount} onChange={(e) => update("supportAmount", e.target.value)} className={INPUT} /></Field><Field label="지원 기간" required><select value={form.supportPeriod} onChange={(e) => update("supportPeriod", e.target.value)} className={INPUT}>{["1개월", "2개월", "3개월", "6개월", "직접 협의"].map((v) => <option key={v}>{v}</option>)}</select></Field></div></>}
          <Field label="입주 가능일" required><div className="relative"><CalendarDays className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--brand-purple)]" /><input type="date" value={form.moveInDate} onChange={(e) => update("moveInDate", e.target.value)} className={cn(INPUT, "pl-10")} /></div></Field>
        </Card>
      </>}
      {step === 2 && <><Card icon={<ImagePlus className="h-[18px] w-[18px]" />} title="매물 사진"><Field label="사진 첨부" hint="선택 · 최대 10장"><label htmlFor={`listing-images-${kind}`} className="flex cursor-pointer flex-col items-center rounded-[18px] border-2 border-dashed border-[#D9D3E1] bg-[#FAF9FB] px-4 py-8 text-center active:bg-[var(--brand-purple-soft)]"><span className="grid h-12 w-12 place-items-center rounded-[16px] bg-[var(--brand-purple-soft)] text-[var(--brand-purple)]"><Upload className="h-6 w-6" /></span><strong className="mt-3 text-[13px] text-[var(--brand-ink)]">사진을 선택해 주세요</strong><span className="mt-1 text-[10.5px] text-[var(--text-muted)]">JPG, PNG · 첫 번째 사진이 대표 이미지</span></label><input id={`listing-images-${kind}`} type="file" accept="image/*" multiple className="hidden" onChange={(e) => setFiles(Array.from(e.target.files ?? []).slice(0, 10).map((file) => file.name))} /></Field>{files.map((file, index) => <div key={`${file}-${index}`} className="flex items-center gap-3 rounded-[13px] bg-[var(--surface-muted)] px-3 py-2.5"><ImagePlus className="h-4 w-4 text-[var(--brand-purple)]" /><span className="min-w-0 flex-1 truncate text-[11.5px] font-bold">{file}</span><button type="button" onClick={() => setFiles((current) => current.filter((_, i) => i !== index))} aria-label={`${file} 삭제`}><X className="h-4 w-4" /></button></div>)}</Card><Card icon={<ClipboardCheck className="h-[18px] w-[18px]" />} title="매물 설명"><Field label="상세 설명" required hint={`${form.description.length}/500`}><textarea value={form.description} onChange={(e) => update("description", e.target.value.slice(0, 500))} rows={7} className={cn(INPUT, "resize-none leading-6")} /></Field><div className="rounded-[14px] border border-[#D7AE54]/25 bg-[#FFF9E9] px-4 py-3 text-[11px] leading-5 text-[#6B5522]">정확한 가격과 실제 사진을 등록하면 승인 검토가 빨라집니다. 개인정보는 설명에 입력하지 마세요.</div></Card></>}
      {step === 3 && <><div className="rounded-[22px] bg-[var(--brand-ink)] p-5 text-white shadow-[0_12px_28px_rgba(27,23,38,.15)]"><span className="gold-fill inline-flex rounded-full px-3 py-1 text-[9px] font-black tracking-[.7px]">REGISTRATION PREVIEW</span><h1 className="mt-4 text-[21px] font-black tracking-[-.5px]">{form.complexName}</h1><p className="mt-1 text-[11.5px] text-white/55">{form.address}</p><div className="mt-5 flex items-end justify-between"><div><p className="text-[10px] text-white/45">{isTransfer ? "희망 매매가" : `${form.benefitType} · ${form.supportPeriod}`}</p><p className="gold-text mt-1 text-[19px] font-black">{isTransfer ? formatMoney(form.askingPrice) : `월 ${formatMoney(form.monthlyRent)}`}</p></div><span className="rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-bold">{form.propertyType}</span></div></div><Card icon={<ClipboardCheck className="h-[18px] w-[18px]" />} title="등록 정보 확인"><SummaryRow label="동·호수" value={`${form.buildingNo}동 ${form.unitNo}호`} /><SummaryRow label="면적·층·방향" value={`${form.area} · ${form.floor}층 · ${form.direction}`} />{isTransfer ? <><SummaryRow label="분양가" value={formatMoney(form.salePrice)} /><SummaryRow label="프리미엄" value={premium} strong /><SummaryRow label="대출 조건" value={form.loan} /></> : <><SummaryRow label="보증금 / 월세" value={`${formatMoney(form.deposit)} / ${formatMoney(form.monthlyRent)}`} /><SummaryRow label="제공 혜택" value={`${form.benefitType} ${form.supportPeriod}`} strong /><SummaryRow label="총 지원금" value={formatMoney(form.supportAmount)} /></>}<SummaryRow label="입주 가능일" value={form.moveInDate} /><SummaryRow label="첨부 사진" value={files.length ? `${files.length}장` : "첨부 안 함"} /></Card><div className="rounded-[18px] border border-[var(--line)] bg-white p-4"><p className="text-[12px] font-black">매물 설명</p><p className="mt-2 text-[11.5px] leading-5 text-[var(--text-muted)]">{form.description}</p></div></>}
    </div>
    <div className="fixed bottom-0 left-1/2 z-40 flex w-full max-w-[430px] -translate-x-1/2 gap-2 border-t border-[var(--line)] bg-white/95 px-4 pb-[max(14px,env(safe-area-inset-bottom))] pt-3 backdrop-blur-xl">{step > 1 && <button type="button" onClick={previous} className="w-[96px] rounded-[15px] border border-[var(--line)] bg-white py-4 text-[13px] font-extrabold">이전</button>}<button type="button" onClick={next} className="flex flex-1 items-center justify-center gap-1 rounded-[15px] bg-[var(--brand-purple)] py-4 text-[14px] font-black text-white shadow-[0_7px_18px_rgba(123,47,247,.28)]">{step === 3 ? "매물 등록하기" : "다음 단계"}<ChevronRight className="h-4 w-4" /></button></div>
  </MobileLayout>;
}
